import turtle

turtle.bgcolor('skyblue')
zolw = turtle.Turtle()
zolw.shape('turtle')
zolw.color('green')
zolw.penup()
zolw.goto(0,200)
zolw.pendown()
zolw.right(45)
zolw.forward(100)
zolw.color('red')
zolw.begin_fill()
zolw.circle(10)
zolw.end_fill()
zolw.color('green')
zolw.right(135)
zolw.forward(50)
zolw.left(135)
zolw.forward(100)
zolw.color('yellow')
zolw.begin_fill()
zolw.circle(10)
zolw.end_fill()
zolw.color('green')
zolw.right(135)
zolw.forward(50)
zolw.left(135)
zolw.forward(100)
zolw.color('blue')
zolw.begin_fill()
zolw.circle(10)
zolw.end_fill()
zolw.color('green')
zolw.right(135)
zolw.forward(50)
zolw.left(135)
zolw.forward(100)
zolw.color('purple')
zolw.begin_fill()
zolw.circle(10)
zolw.end_fill()
zolw.color('green')
zolw.penup()
zolw.goto(0,200)
zolw.pendown()
zolw.right(90)
zolw.forward(100)
zolw.color('red')
zolw.begin_fill()
zolw.circle(10)
zolw.end_fill()
zolw.color('green')
zolw.left(135)
zolw.forward(50)
zolw.right(135)
zolw.forward(100)
zolw.color('purple')
zolw.begin_fill()
zolw.circle(10)
zolw.end_fill()
zolw.color('green')
zolw.left(135)
zolw.forward(50)
zolw.right(135)
zolw.forward(100)
zolw.color('white')
zolw.begin_fill()
zolw.circle(10)
zolw.end_fill()
zolw.color('green')
zolw.left(135)
zolw.forward(50)
zolw.right(135)
zolw.forward(100)
zolw.color('pink')
zolw.begin_fill()
zolw.circle(10)
zolw.end_fill()
zolw.color('green')
zolw.left(135)
zolw.forward(265)
zolw.right(180)
zolw.forward(100)
zolw.left(90)
zolw.color('brown')
zolw.forward(65)
zolw.right(90)
zolw.forward(50)
zolw.right(90)
zolw.forward(65)
turtle.exitonclick()








# 
# t.color('brown')

